# Generated by Django 4.0.5 on 2022-07-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkAuthor',
            fields=[
                ('authorid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bk_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BkBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.BigIntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pubdate', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bk_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BkPublisher',
            fields=[
                ('pubid', models.AutoField(primary_key=True, serialize=False)),
                ('pubname', models.CharField(max_length=200)),
                ('pubcontact', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'bk_publisher',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
